---
name: Merge and update myfilters.txt
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run script and commit and push changes
        id: run-script-and-commit
        run: sh merge.sh && sh commit.sh
...